{
 "title": "OpenIaaS - VMs lists",
 "tags": [
  "vm",
  "vates",
  "xoa",
  "deep-dive"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Tenants",
    "label": "Tenants",
    "query": {
     "query": "label_values(vates_vm_info_gauge,tenant_name)"
    }
   },
   {
    "name": "XOAs",
    "label": "XOAs",
    "query": {
     "query": "label_values(vates_vm_info_gauge{tenant_name=~\"$Tenants\"},xoa_hostname)"
    }
   },
   {
    "name": "Pools",
    "label": "Pools",
    "query": {
     "query": "label_values(vates_vm_info_gauge{tenant_name=~\"$Tenants\", xoa_hostname=~\"$XOAs\"},pool_name)"
    }
   },
   {
    "name": "VMs",
    "label": "VMs",
    "query": {
     "query": "label_values(vates_vm_info_gauge{tenant_name=~\"$Tenants\", xoa_hostname=~\"$XOAs\", pool_name=~\"$Pools\"},vm_name)"
    }
   },
   {
    "name": "stat",
    "label": "stat",
    "query": {
     "query": "label_values(vates_vm_cpu_usage_percent_gauge,stat)"
    }
   },
   {
    "name": "vif",
    "label": "vif",
    "query": {
     "query": "label_values(vates_vm_network_rx_bytes_gauge,vif)"
    }
   },
   {
    "name": "xvd",
    "label": "xvd",
    "query": {
     "query": "label_values(vates_vm_disk_read_bytes_gauge,xvd)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "VM: $VMs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "VMs" },
  {
   "title": "vCPUs",
   "type": "stat",
   "description": "vCPUs",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vates_vm_vcpus_gauge{tenant_name=~\"$Tenants\", xoa_hostname=~\"$XOAs\", pool_name=~\"$Pools\", vm_name=~\"$VMs\"}",
     "legendFormat": "vCPUs"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "stat",
   "description": "Memory usage",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vates_vm_cpu_usage_percent_gauge{tenant_name=~\"$Tenants\", xoa_hostname=~\"$XOAs\", pool_name=~\"$Pools\", vm_name=~\"$VMs\", stat=~\"$stat\"}",
     "legendFormat": "Mem % {{stat}}"
    }
   ]
  },
  {
   "title": "Memory %",
   "type": "stat",
   "description": "Memory usage",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vates_vm_memory_percent_gauge{tenant_name=~\"$Tenants\", xoa_hostname=~\"$XOAs\", pool_name=~\"$Pools\", vm_name=~\"$VMs\", stat=~\"$stat\"}",
     "legendFormat": "Mem % {{stat}}"
    }
   ]
  },
  {
   "title": "Disk total size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vates_vm_disk_total_size_bytes_gauge{tenant_name=~\"$Tenants\", xoa_hostname=~\"$XOAs\", pool_name=~\"$Pools\", vm_name=~\"$VMs\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vates_vm_disks_count_gauge{tenant_name=~\"$Tenants\", xoa_hostname=~\"$XOAs\", pool_name=~\"$Pools\", vm_name=~\"$VMs\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "description": "Memory used (bytes)",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "vates_vm_memory_used_bytes_gauge{tenant_name=~\"$Tenants\", xoa_hostname=~\"$XOAs\", pool_name=~\"$Pools\", vm_name=~\"$VMs\", stat=~\"$stat\"}",
     "legendFormat": "Mem used {{stat}}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM (bytes)",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vates_vm_memory_total_bytes_gauge{tenant_name=~\"$Tenants\", xoa_hostname=~\"$XOAs\", pool_name=~\"$Pools\", vm_name=~\"$VMs\"}",
     "legendFormat": "RAM Total"
    }
   ]
  },
  {
   "title": "Eternet Interface",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vates_vm_network_interfaces_count_gauge{tenant_name=~\"$Tenants\", xoa_hostname=~\"$XOAs\", pool_name=~\"$Pools\", vm_name=~\"$VMs\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "XOA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vates_vm_info_gauge{tenant_name=~\"$Tenants\", xoa_hostname=~\"$XOAs\", pool_name=~\"$Pools\", vm_name=~\"$VMs\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AZ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vates_vm_info_gauge{tenant_name=~\"$Tenants\", xoa_hostname=~\"$XOAs\", pool_name=~\"$Pools\", vm_name=~\"$VMs\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "snapshots count",
   "type": "stat",
   "description": "vCPUs",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vates_vm_snapshots_count_gauge{tenant_name=~\"$Tenants\", xoa_hostname=~\"$XOAs\", pool_name=~\"$Pools\", vm_name=~\"$VMs\"}",
     "legendFormat": "vCPUs"
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vates_vm_running_gauge{tenant_name=~\"$Tenants\", xoa_hostname=~\"$XOAs\", pool_name=~\"$Pools\", vm_name=~\"$VMs\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "timeseries",
   "description": "Disk IOPS",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "vates_vm_iops_read_total_gauge{tenant_name=~\"$Tenants\", xoa_hostname=~\"$XOAs\", pool_name=~\"$Pools\", vm_name=~\"$VMs\", stat=~\"$stat\"}",
     "legendFormat": "IOPS Read {{stat}}"
    },
    {
     "expr": "vates_vm_iops_write_total_gauge{tenant_name=~\"$Tenants\", xoa_hostname=~\"$XOAs\", pool_name=~\"$Pools\", vm_name=~\"$VMs\", stat=~\"$stat\"}",
     "legendFormat": "IOPS Write {{stat}}"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "timeseries",
   "description": "CPU usage %",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vates_vm_cpu_usage_percent_gauge{tenant_name=~\"$Tenants\", xoa_hostname=~\"$XOAs\", pool_name=~\"$Pools\", vm_name=~\"$VMs\", stat=~\"$stat\"}",
     "legendFormat": "CPU {{stat}}"
    }
   ]
  },
  {
   "title": "Memory %",
   "type": "timeseries",
   "description": "Memory usage",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vates_vm_memory_percent_gauge{tenant_name=~\"$Tenants\", xoa_hostname=~\"$XOAs\", pool_name=~\"$Pools\", vm_name=~\"$VMs\", stat=~\"$stat\"}",
     "legendFormat": "Mem % {{stat}}"
    }
   ]
  },
  {
   "title": "Per-interface RX+TX (instant)",
   "type": "barchart",
   "description": "Per-interface (vif) instantaneous RX/TX (top 10)",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(10, vates_vm_network_rx_bytes_gauge{tenant_name=~\"$Tenants\", xoa_hostname=~\"$XOAs\", pool_name=~\"$Pools\", vm_name=~\"$VMs\", vif=~\"$vif\", stat=~\"$stat\"} + vates_vm_network_tx_bytes_gauge{tenant_name=~\"$Tenants\", xoa_hostname=~\"$XOAs\", pool_name=~\"$Pools\", vm_name=~\"$VMs\", vif=~\"$vif\", stat=~\"$stat\"})",
     "legendFormat": "{{vif}}"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "timeseries",
   "description": "Disk throughput (bytes/s)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "vates_vm_disk_read_total_bytes_gauge{tenant_name=~\"$Tenants\", xoa_hostname=~\"$XOAs\", pool_name=~\"$Pools\", vm_name=~\"$VMs\", stat=~\"$stat\"}",
     "legendFormat": "Read {{stat}}"
    },
    {
     "expr": "vates_vm_disk_write_total_bytes_gauge{tenant_name=~\"$Tenants\", xoa_hostname=~\"$XOAs\", pool_name=~\"$Pools\", vm_name=~\"$VMs\", stat=~\"$stat\"}",
     "legendFormat": "Write {{stat}}"
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "timeseries",
   "description": "Network throughput (bytes/s)",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "vates_vm_network_rx_total_bytes_gauge{tenant_name=~\"$Tenants\", xoa_hostname=~\"$XOAs\", pool_name=~\"$Pools\", vm_name=~\"$VMs\", stat=~\"$stat\"}",
     "legendFormat": "RX {{stat}}"
    },
    {
     "expr": "vates_vm_network_tx_total_bytes_gauge{tenant_name=~\"$Tenants\", xoa_hostname=~\"$XOAs\", pool_name=~\"$Pools\", vm_name=~\"$VMs\", stat=~\"$stat\"}",
     "legendFormat": "TX {{stat}}"
    }
   ]
  }
 ]
}