{
 "title": "OpenIaaS - Backup Vms",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "tenant_name",
    "query": {
     "query": "label_values(vates_backup_job_info_gauge,tenant_name)"
    }
   },
   {
    "name": "az",
    "query": {
     "query": "label_values(vates_backup_job_info_gauge{tenant_name=~\"$tenant_name\"},az)"
    }
   },
   {
    "name": "job_name",
    "query": {
     "query": "label_values(vates_backup_job_info_gauge{tenant_name=~\"$tenant_name\", az=~\"$az\"},job_name)"
    }
   },
   {
    "name": "vm_name",
    "query": {
     "query": "label_values(vates_vm_backup_age_hours_gauge{tenant_name=~\"$tenant_name\", az=~\"$az\", job_name=~\"$job_name\"},vm_name)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "VM Deep Dive: $vm_name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "vm_name" },
  {
   "title": "Last Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(vates_vm_backup_last_status_gauge{tenant_name=~\"$tenant_name\", az=~\"$az\", job_name=~\"$job_name\", vm_name=\"$vm_name\"}[$__range])",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Age",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(vates_vm_backup_age_hours_gauge{tenant_name=~\"$tenant_name\", az=~\"$az\", job_name=~\"$job_name\", vm_name=\"$vm_name\"}[$__range])",
     "legendFormat": "Age"
    }
   ]
  },
  {
   "title": "Last Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(vates_vm_backup_duration_seconds_gauge{tenant_name=~\"$tenant_name\", az=~\"$az\", job_name=~\"$job_name\", vm_name=\"$vm_name\"}[$__range])",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "Last Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(vates_vm_backup_size_bytes_gauge{tenant_name=~\"$tenant_name\", az=~\"$az\", job_name=~\"$job_name\", vm_name=\"$vm_name\"}[$__range])",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Backup Duration History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "vates_vm_backup_duration_seconds_gauge{tenant_name=~\"$tenant_name\", az=~\"$az\", job_name=~\"$job_name\", vm_name=\"$vm_name\"}",
     "legendFormat": "Total Duration"
    }
   ]
  },
  {
   "title": "Backup Size History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "vates_vm_backup_size_bytes_gauge{tenant_name=~\"$tenant_name\", az=~\"$az\", job_name=~\"$job_name\", vm_name=\"$vm_name\"}",
     "legendFormat": "Size"
    }
   ]
  }
 ]
}