{
 "title": "VMware vSphere  - VMs",
 "description": "VMware vSphere Dashboard - VMs (Grafana 8.x)",
 "tags": [
  "VMware",
  "vSphere VM",
  "vSphere Telegraf",
  "MetricsQL/PromQL",
  "CloudTemple"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "inter",
    "label": "Sampling",
    "query": "20s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "db", "label": "db", "query": "telegraf" },
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "vcenter",
    "label": "vCenter Server",
    "query": {
     "query": "label_values(vsphere_host_cpu_usage_average{db=\"$db\"}, vcenter)"
    }
   },
   {
    "name": "clustername",
    "label": "Cluster",
    "query": {
     "query": "label_values(vsphere_host_cpu_usage_average{db=\"$db\",vcenter=\"$vcenter\"}, clustername)"
    }
   },
   {
    "name": "virtualmachine",
    "label": "VM",
    "query": {
     "query": "label_values(vsphere_vm_cpu_usage_average{db=\"$db\",vcenter=\"$vcenter\",clustername=\"$clustername\"}, vmname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$virtualmachine - Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "virtualmachine",
   "collapsed": true,
   "panels": [
    {
     "title": "VM Quick Overview",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Uptime",
       "expr": "max by (vmname) (vsphere_vm_sys_uptime_latest{vmname=~\"${virtualmachine}\"})",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_vm_sys",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_vm_sys\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime_latest\")\r\n  |> filter(fn: (r) => r[\"vmname\"] =~ /${virtualmachine:regex}/)\r\n  |> group(columns: [\"vmname\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
       "select": [
        [
         { "params": [ "uptime_latest" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
       ]
      },
      {
       "alias": "CPU Usage MHz",
       "expr": "max by (vmname) (vsphere_vm_cpu_usagemhz_average{vmname=~\"${virtualmachine}\"})",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_vm_cpu",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_vm_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usagemhz_average\")\r\n  |> filter(fn: (r) => r[\"vmname\"] =~ /${virtualmachine:regex}/)\r\n  |> group(columns: [\"vmname\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
       "select": [
        [
         { "params": [ "usagemhz_average" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
       ]
      },
      {
       "alias": "RAM Usage",
       "expr": "max by (vmname) (vsphere_vm_mem_active_average{vmname=~\"${virtualmachine}\"})",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_vm_mem",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_vm_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"active_average\")\r\n  |> filter(fn: (r) => r[\"vmname\"] =~ /${virtualmachine:regex}/)\r\n  |> group(columns: [\"vmname\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
       "select": [
        [
         { "params": [ "active_average" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
       ]
      },
      {
       "alias": "CPU Usage %",
       "expr": "max by (vmname) (vsphere_vm_cpu_usage_average{vmname=~\"${virtualmachine}\"})",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_vm_cpu",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_vm_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_average\")\r\n  |> filter(fn: (r) => r[\"vmname\"] =~ /${virtualmachine:regex}/)\r\n  |> group(columns: [\"vmname\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
       ]
      },
      {
       "alias": "RAM Usage %",
       "expr": "max by (vmname) (vsphere_vm_mem_usage_average{vmname=~\"${virtualmachine}\"})",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_vm_mem",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_vm_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_average\")\r\n  |> filter(fn: (r) => r[\"vmname\"] =~ /${virtualmachine:regex}/)\r\n  |> group(columns: [\"vmname\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
       ]
      }
     ]
    },
    {
     "title": "CPU Usage in %",
     "type": "timeseries",
     "description": "CPU usage as a percentage during the interval.",
     "gridPos": { "h": 7, "w": 7, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "CPU usage %",
       "expr": "avg by (vmname) (vsphere_vm_cpu_usage_average{cpu=\"instance-total\",vmname=~\"${virtualmachine}\"})",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "vmname" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_vm_cpu",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_vm_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_average\")\r\n  |> filter(fn: (r) => r[\"cpu\"] == \"instance-total\")\r\n  |> filter(fn: (r) => r[\"vmname\"] =~ /${virtualmachine:regex}/)\r\n  |> group(columns: [\"vmname\",\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
       ]
      },
      {
       "alias": "CPU Ready %",
       "expr": "avg by (vmname) (vsphere_vm_cpu_readiness_average{vmname=~\"${virtualmachine}\"})",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "vmname" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_vm_cpu",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_vm_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"readiness_average\")\r\n  |> filter(fn: (r) => r[\"vmname\"] =~ /${virtualmachine:regex}/)\r\n  |> group(columns: [\"vmname\",\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
       "select": [
        [
         { "params": [ "readiness_average" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
       ]
      }
     ]
    },
    {
     "title": "RAM Utilization",
     "type": "timeseries",
     "description": "Amount of guest physical memory that is being actively read or written by guest. Activeness is estimated by ESXi.",
     "gridPos": { "h": 7, "w": 6, "x": 13, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "RAM usage %",
       "expr": "avg by (vmname) (vsphere_vm_mem_usage_average{vmname=~\"${virtualmachine}\"})",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "vmname" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_vm_mem",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_vm_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_average\")\r\n  |> filter(fn: (r) => r[\"vmname\"] =~ /${virtualmachine:regex}/)\r\n  |> group(columns: [\"vmname\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
       ]
      }
     ]
    },
    {
     "title": "CPU Ready in miliseconds",
     "type": "timeseries",
     "description": "Time that the virtual machine was ready, but could not get scheduled to run on the physical CPU during last measurement interval.",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "Core $tag_cpu",
       "expr": "avg by (vmname) (vsphere_vm_cpu_ready_summation{vmname=~\"${virtualmachine}\"})",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "vmname" ], "type": "tag" },
        { "params": [ "cpu" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_vm_cpu",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_vm_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ready_summation\")\r\n  |> filter(fn: (r) => r[\"vmname\"] =~ /${virtualmachine:regex}/)\r\n  |> group(columns: [\"vmname\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
       "select": [
        [
         { "params": [ "ready_summation" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Usage",
     "type": "timeseries",
     "description": "Network utilization (combined transmit-rates and receive-rates) during the interval.",
     "gridPos": { "h": 6, "w": 13, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "alias": "$tag_interface bytesRx",
       "expr": "avg by (interface) (vsphere_vm_net_bytesRx_average{vmname=~\"${virtualmachine}\"})",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "legendFormat": "bytes_Rx_{{interface}}",
       "measurement": "vsphere_vm_net",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_vm_net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytesRx_average\")\r\n  |> filter(fn: (r) => r[\"vmname\"] =~ /${virtualmachine:regex}/)\r\n  |> group(columns: [\"_field\",\"interface\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
       "select": [
        [
         { "params": [ "bytesRx_average" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
       ]
      },
      {
       "alias": "$tag_interface bytesTx",
       "expr": "avg by (interface) (vsphere_vm_net_bytesTx_average{vmname=~\"${virtualmachine}\"})",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "legendFormat": "bytes_Tx_{{vmname}}_{{interface}}",
       "measurement": "vsphere_vm_net",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_vm_net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytesTx_average\")\r\n  |> filter(fn: (r) => r[\"vmname\"] =~ /${virtualmachine:regex}/)\r\n  |> group(columns: [\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
       "select": [
        [
         { "params": [ "bytesTx_average" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
       ]
      }
     ]
    },
    {
     "title": "Total Disk Latency",
     "type": "timeseries",
     "description": "The average time a read, or write, from the virtual disk takes.",
     "gridPos": { "h": 6, "w": 6, "x": 13, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "Write - $tag_disk",
       "expr": "vsphere_vm_virtualDisk_totalReadLatency_average{vmname=~\"${virtualmachine}\"}",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "disk" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "legendFormat": "ReadLatency_{{disk}}",
       "measurement": "vsphere_vm_virtualDisk",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_vm_virtualDisk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"totalReadLatency_average\")\r\n  |> filter(fn: (r) => r[\"vmname\"] =~ /${virtualmachine:regex}/)\r\n  |> group(columns: [\"_field\",\"disk\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n  ",
       "select": [
        [
         { "params": [ "totalWriteLatency_average" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
       ]
      },
      {
       "alias": "Read - $tag_disk",
       "expr": "vsphere_vm_virtualDisk_totalWriteLatency_average{vmname=~\"${virtualmachine}\"}",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "disk" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "legendFormat": "WriteLatency_{{disk}}",
       "measurement": "vsphere_vm_virtualDisk",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_vm_virtualDisk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"totalWriteLatency_average\")\r\n  |> filter(fn: (r) => r[\"vmname\"] =~ /${virtualmachine:regex}/)\r\n  |> group(columns: [\"_field\",\"disk\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n  ",
       "select": [
        [
         { "params": [ "totalReadLatency_average" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
       ]
      }
     ]
    },
    {
     "title": "Storage Adapter Latency",
     "type": "timeseries",
     "description": "The average time a read, or write, from the datastore takes.",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "ReadAverage $tag_disk",
       "expr": "avg by (vmname) (vsphere_vm_datastore_totalReadLatency_average{vmname=~\"${virtualmachine}\"})",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "disk" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "legendFormat": "numberReadAveraged_average",
       "measurement": "vsphere_vm_virtualDisk",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_vm_datastore\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"totalReadLatency_average\")\r\n  |> filter(fn: (r) => r[\"vmname\"] =~ /${virtualmachine:regex}/)\r\n  |> group(columns: [\"_field\",\"disk\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n  ",
       "select": [
        [
         { "params": [ "totalReadLatency_average" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
       ]
      },
      {
       "alias": "WriteAverage $tag_disk",
       "expr": "avg by (vmname) (vsphere_vm_datastore_totalWriteLatency_average{vmname=~\"${virtualmachine}\"})",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "disk" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "legendFormat": "numberWriteAveraged_average",
       "measurement": "vsphere_vm_virtualDisk",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_vm_datastore\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"totalWriteLatency_average\")\r\n  |> filter(fn: (r) => r[\"vmname\"] =~ /${virtualmachine:regex}/)\r\n  |> group(columns: [\"_field\",\"disk\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n  ",
       "select": [
        [
         { "params": [ "totalWriteLatency_average" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "$virtualmachine - Storage Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "virtualmachine"
  },
  {
   "title": "IO Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "vsphere_vm_virtualDisk_readIOSize_latest{vmname=~\"${virtualmachine}\"}",
     "legendFormat": "Read_IO_size_{{esxhostname}}"
    },
    {
     "expr": "vsphere_vm_virtualDisk_writeIOSize_latest{vmname=~\"${virtualmachine}\"}",
     "legendFormat": "Write_IO_size_{{esxhostname}}"
    }
   ]
  },
  {
   "title": "IO Read/Write Latest",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "vsphere_vm_virtualDisk_readOIO_latest{vmname=~\"${virtualmachine}\"}",
     "legendFormat": "Read_IO_{{esxhostname}}"
    },
    {
     "expr": "vsphere_vm_virtualDisk_writeOIO_latest{vmname=~\"${virtualmachine}\"}",
     "legendFormat": "Write_IO_{{esxhostname}}"
    }
   ]
  },
  {
   "title": "Latency Read/Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vsphere_vm_virtualDisk_readLatencyUS_latest{vmname=~\"${virtualmachine}\"}",
     "legendFormat": "Read_Latency_{{esxhostname}}"
    },
    {
     "expr": "vsphere_vm_virtualDisk_writeLatencyUS_latest{vmname=~\"${virtualmachine}\"}",
     "legendFormat": "Write_Latency_{{esxhostname}}"
    }
   ]
  }
 ]
}