{
 "title": "VMware vSphere - Datastore",
 "description": "VMware vSphere Dashboard - Datastore (Grafana 8.x)",
 "tags": [
  "VMware",
  "vSphere Datastore",
  "vSphere Telegraf",
  "CloudTemple",
  "MetricsQL/PromQL"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "db", "label": "db", "query": "telegraf" },
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "vcentername",
    "label": "vCenter Server",
    "query": {
     "query": "label_values(vsphere_host_cpu_usage_average{db=\"$db\"}, vcenter)"
    }
   },
   {
    "name": "datastore",
    "label": "Datastore",
    "query": {
     "query": "label_values(vsphere_host_datastore_read_average{db=\"$db\",vcenter=\"${vcentername}\"}, dsname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Capacity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total Capacity",
     "expr": "avg by (dsname) (vsphere_datastore_disk_capacity_latest{dsname=~\"${datastore}\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_datastore_disk",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_datastore_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"capacity_latest\")\r\n  |> filter(fn: (r) => r[\"source\"] =~ /${datastore:regex}/)\r\n  |> group(columns: [\"source\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "capacity_latest" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$datastore$/" }
     ]
    },
    {
     "alias": "Free Capacity",
     "expr": "avg by (dsname) (vsphere_datastore_disk_capacity_latest{dsname=~\"${datastore}\"}) - avg by (dsname) (vsphere_datastore_disk_used_latest{dsname=~\"${datastore}\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_datastore_disk",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_datastore_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"capacity_latest\" or r[\"_field\"] == \"used_latest\")\r\n  |> filter(fn: (r) => r[\"source\"] =~ /${datastore:regex}/)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with  _value: float(v: r.capacity_latest) - float(v: r.used_latest) }))\r\n  |> group(columns: [\"source\",\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "capacity_latest" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$datastore$/" }
     ]
    }
   ]
  },
  {
   "title": "Datastores - Usage Capacity",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_source",
     "expr": "avg by (dsname) (vsphere_datastore_disk_used_latest{dsname=~\"${datastore}\"}) / avg by (dsname) (vsphere_datastore_disk_capacity_latest{dsname=~\"${datastore}\"}) * 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{dsname}}",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_datastore_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"capacity_latest\" or r[\"_field\"] == \"used_latest\")\r\n  |> filter(fn: (r) => r[\"source\"] =~ /${datastore:regex}/)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with  _value: float(v: r.used_latest) / float(v: r.capacity_latest) * 100.0 }))\r\n  |> group(columns: [\"source\",\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Capacity Summary",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total Capacity",
     "expr": "avg by (dsname) (vsphere_datastore_disk_used_latest{dsname=~\"${datastore}\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_datastore_disk",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_datastore_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"used_latest\")\r\n  |> filter(fn: (r) => r[\"source\"] =~ /${datastore:regex}/)\r\n  |> group(columns: [\"source\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "capacity_latest" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$datastore$/" }
     ]
    },
    {
     "alias": "Free Capacity",
     "expr": "avg by (dsname) (vsphere_datastore_disk_capacity_latest{dsname=~\"${datastore}\"}) - avg by (dsname) (vsphere_datastore_disk_used_latest{dsname=~\"${datastore}\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_datastore_disk",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_datastore_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"capacity_latest\" or r[\"_field\"] == \"used_latest\")\r\n  |> filter(fn: (r) => r[\"source\"] =~ /${datastore:regex}/)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with  _value: float(v: r.capacity_latest) - float(v: r.used_latest) }))\r\n  |> group(columns: [\"source\",\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "capacity_latest" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$datastore$/" }
     ]
    }
   ]
  },
  {
   "title": "Datastore IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "vsphere_host_datastore_datastoreIops_average{dsname=~\"${datastore}\"}",
     "legendFormat": "{{esxhostname}}"
    }
   ]
  },
  {
   "title": "Datastore Latency (Read/Write)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vsphere_host_datastore_totalReadLatency_average{dsname=~\"${datastore}\"}",
     "legendFormat": "Read_{{esxhostname}}"
    },
    {
     "expr": "vsphere_host_datastore_totalWriteLatency_average{dsname=~\"${datastore}\"}",
     "legendFormat": "Write_{{esxhostname}}"
    }
   ]
  }
 ]
}