{
 "title": "Housing - Power",
 "description": "Tableau de bord pour visualiser la consommation d'énergie",
 "tags": [
  "VMware",
  "Power Overview",
  "vSphere Telegraph"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "db", "label": "db", "query": "telegraf" },
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "AZ", "label": "AZ", "query": { "query": "label_values(site_pdu)" } }
  ]
 },
 "panels": [
  {
   "title": "Consumption Global (kw) (avg_over_time)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time((device_pdu_power_gauge_value{site_pdu=~\"$AZ\"}[$__range])/ 100)) by (tenant)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Racks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(device_pdu_power_gauge_value{site_pdu=~\"$AZ\"}) / 2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Puissance in KW for all sites ",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(device_pdu_power_gauge_value{site_pdu=~\"$AZ\"} / 100) by (site_pdu)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Puissance by rack of tenant (kw)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(device_pdu_power_gauge_value{site_pdu=~\"$AZ\"} / 100) by(site_pdu, rack,rack_role,rack_tenant) ",
     "legendFormat": "{{site_pdu}} - {{rack}}"
    }
   ]
  },
  {
   "title": "3 Kw * rack count ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(device_pdu_power_gauge_value{site_pdu=~\"$AZ\"}) / 2 ) * 3",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Aditionnal power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round((sum(avg_over_time((device_pdu_power_gauge_value{site_pdu=~\"$AZ\"}[$__range])/ 100)) by (tenant)) - ((count(device_pdu_power_gauge_value{site_pdu=~\"$AZ\"}) / 2 ) * 3), 2)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumption per Rack (kw) (avg_over_time)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time((device_pdu_power_gauge_value{site_pdu=~\"$AZ\"}[$__range])/ 100)) by (site_pdu, rack,rack_role,rack_tenant)",
     "legendFormat": "{{site_pdu}} - {{rack}}"
    }
   ]
  },
  {
   "title": "Power by rack",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by(site_pdu, rack,rack_role,rack_tenant) (device_pdu_power_gauge_value{site_pdu=~\"$AZ\"}) /100",
     "legendFormat": "{{site_pdu}} - {{rack}}"
    }
   ]
  }
 ]
}