{
 "title": "New dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device",
    "query": {
     "query": "label_values(network_bytes_in_counter_value,ngbr)"
    }
   },
   {
    "name": "site",
    "query": {
     "query": "label_values(network_bytes_in_counter_value,site)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Housing top consumers",
   "type": "timeseries",
   "description": "Trafic in / out from the device point of view\nMetered on the top of rack",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum by(ngbr, site) (rate(network_bytes_in_counter_value{site=~\"$site\"}[$__rate_interval])) * 8",
     "legendFormat": "{{ngbr}} ({{site}}) - out"
    },
    {
     "expr": "sum by(ngbr, site) (rate(network_bytes_out_counter_value{site=~\"$site\"}[$__rate_interval])) * -8",
     "legendFormat": "{{ngbr}} ({{site}}) - in"
    }
   ]
  },
  {
   "title": "Housing trafic direction by site 95%",
   "type": "barchart",
   "description": "Trafic in / out from the datacenter point of view excluding top 5% peaks\nMetered on the top of rack\n",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "label_replace(sort_desc(sum by(site) (rate(network_bytes_in_counter_value[$__rate_interval]))) * 8, \"site\", \"$1 - in\", \"site\", \"(.*)\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(sort_desc(sum by(site) (rate(network_bytes_out_counter_value[$__rate_interval]))) * 8, \"site\", \"$1 - out\", \"site\", \"(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "interfaces detail for : $device",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "$device",
   "type": "timeseries",
   "description": "Trafic in / out from the device point of view\nMetered on the top of rack\n",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "repeat": "device",
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "rate(network_bytes_in_counter_value{ngbr=\"$device\"}[$__rate_interval]) * 8",
     "legendFormat": "{{ngbr}} ({{site}})- interface \"{{nif}}\" - out"
    },
    {
     "expr": "rate(network_bytes_out_counter_value{ngbr=\"$device\"}[$__rate_interval]) * -8",
     "legendFormat": "{{ngbr}} ({{site}}) - interface \"{{nif}}\" - in"
    }
   ]
  }
 ]
}